server:
  port: 8888

logging:
  file:
    path: /logs
    name: /logs/localtest.log

spring:
  application:
    name: localTestTwo
  datasource:
    drver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.88.68:3306/local_test?serverTimezone=UTC
    username: root
    password: 123456

mybatis:
  type-aliases-package: com.localtest.model
  mapper-locations:
    - mapper/*